import 'package:flutter/material.dart';

class Row7 extends StatelessWidget {
  const Row7({super.key});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Expanded(
          flex: 1,
          child: Row(
            // mainAxisAlignment: MainAxisAlignment.start,
            // crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Container(
                color: Colors.red,
                height: 5,
              ),
              const Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('    Airflow  '),
                  Text('    Applications  '),
                  Text('    Desktop  '),
                  Text('    Documents  '),
                  Text('    Downloads  '),
                  Text('    Flutter  '),
                  Text('    Mini  '),
                  Text('    Movies  '),
                  Text('    Music  '),
                  Text('    nltk_data  '),
                  Text('    Picture  '),
                  Text('    Postman  '),
                  Text('    public  '),
                  Text('    Python  '),
                  Text('    C  '),
                  Text('    C++  '),
                  Text('    C#  '),
                  Text('    Ruby  '),
                  Text('    R  '),
                  Text('    Sql  '),
                  Text('    Mysql  '),
                  Text('    development  '),
                  Text('    koorg  '),
                  Text('    uri  '),
                  Text('    Artificial  '),
                  Text('    intelligence  '),
                  Text('    anaconda  '),
                  Text('    scoda  '),
                  Text('    wheel  '),
                  Text('    nokia  '),
                  Text('    bmw  '),
                  Text('    renata  '),
                  Text('    sonata  '),
                ],
              ),
              const Column(
                children: [
                  Text('       ...  '),
                  Text('       ...  '),
                  Text('       ...  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ...  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ...  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ...  '),
                  Text('       ...  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ...  '),
                  Text('       ...  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                  Text('       ext  '),
                ],
              ),
              const Column(
                children: [
                  Text('                   DIR'),
                  Text('                   DIR'),
                  Text('                   ...'),
                  Text('                   ...'),
                  Text('                   ...'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   DIR'),
                  Text('                   DIR'),
                  Text('                   Size'),
                  Text('                   ...'),
                  Text('                   ..'),
                  Text('                   Size'),
                  Text('                   DIR'),
                  Text('                   DIR'),
                  Text('                   DIR'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   ...'),
                  Text('                   ...'),
                  Text('                   ...'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   ...'),
                  Text('                   ...'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   Size'),
                  Text('                   Size'),
                ],
              ),
              const Column(
                children: [
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     ...'),
                  Text('                     6/21/23, 12:22 PM'),
                  Text('                     16/21/23, 12:22 AM'),
                  Text('                     7/21/23, 12:22 PM'),
                  Text('                     8/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     12/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                    ...'),
                  Text('                     ...'),
                  Text('                     6/21/23, 12:22 PM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                    ...'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 PM'),
                  Text('                     6/21/23, 12:22 PM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                    ...'),
                  Text('                     3/21/23, 12:22 PM'),
                  Text('                     4/21/23, 12:22 AM'),
                  Text('                     9/21/23, 12:22 AM'),
                  Text('                     5/21/23, 12:22 PM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 PM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 PM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 AM'),
                  Text('                     6/21/23, 12:22 PM'),
                ],
              ),
              const Column(
                children: [
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                  Text('                     folder'),
                ],
              ),
            ],
          ),
        ),
        Expanded(
          flex: 1,
          child: Row(
            children: [
              Container(
                color: Colors.red,
                height: 5,
              ),
              const Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('    Name  '),
                ],
              ),
              const Column(
                children: [
                  Text('                    ext  '),
                ],
              ),
              const Column(
                children: [
                  Text('                   Size'),
                ],
              ),
              const Column(
                children: [
                  Text('                     Modified'),
                ],
              ),
              const Column(
                children: [
                  Text('                     Kind'),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }
}
